name: Execute microCI pipeline

on: [push]

jobs:
  execute-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run standard Docker container
        run: |
          curl -fsSL github.com/geraldolsribeiro/microci/releases/download/latest/microCI -o microCI
          chmod 755 ./microCI
          mkdir -p ~/.ssh/
          touch ~/.ssh/config
          docker run --rm alpine echo "Hello from inside Docker!"
          ./microCI | bash
